log:
  channel: stack
  level: debug

broadcast:
  driver: log #BROADCAST_DRIVER

cache:
  driver: file #CACHE_DRIVER

filesystem:
  driver: local #FILESYSTEM_DRIVER

queue:
  connection: sync #QUEUE_CONNECTION

session:
  driver: file #SESSION_DRIVER
  lifetime: 120 #SESSION_LIFETIME

