packages:
  required:
    apt:
    - apache2
    - git
    - software-properties-common
    - php8.1
    - php8.1-bcmath
    - php8.1-bz2
    - php8.1-intl
    - php8.1-gd
    - php8.1-mbstring
    - php8.1-mysql
    - php8.1-common
    - php8.1-zip
    - php8.1-curl
    - php8.1-xml
    - php8.1-gmp
    - redis-server
    - supervisor

apache:
  a2enmod:
    module_list:
      - rewrite
      - headers
      - ssl

security:
  app_user: ubuntu
