# Set up apache.server_name if app.url is set removing the http(s)://
- name: Set up apache_server_name from app.url if defined otherwise default to localhost
  shell: "echo '{{ app.url }}' | sed 's/^http[s]*:\\/\\///'"
  when: app.url is defined
  register: apache_server_name

# add-apt-repository
- name: Add repository for PHP 7.4
  apt_repository:
    repo: ppa:ondrej/php

- name: Install required packages
  apt:
    name: "{{ packages.required.apt }}"
    update-cache: yes

- name: Create the app user if it doesn't exist
  user:
    name: "{{ security.app_user }}"
    state: present
    system: yes
    shell: /bin/bash
    create_home: yes

- name: Install Composer
  shell: if [ ! -f /usr/local/bin/composer ]; then curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer; fi
  args:
    chdir: /tmp
  tags:
  - update
  register: composer_install
  changed_when: "'Composer' in composer_install.stdout"
