apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.appName}}-{{.Values.envName}}-cron
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 120
  failedJobsHistoryLimit: 30
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{.Values.appName}}-{{.Values.envName}}-cron
            image: {{.Values.artifactImage}}
            securityContext:
              runAsUser: 0
            args:
            - /bin/sh
            - -c
            - php /app/crontab/cron.php
            envFrom:
            - configMapRef:
                name: {{.Values.appName}}-{{.Values.envName}}-config
            resources:
              requests:
                cpu: "100m"
                memory: "100Mi"
              limits:
                cpu: "200m"
                memory: "200Mi"
          restartPolicy: Never
