---
name: Run linters

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: ["Automated formatters"]
    types:
      - completed

jobs:
  run-linters:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185
        with:
          image: yandex/gixy
          # yamllint disable-line rule:line-length
          options: -v ${{ github.workspace }}/config/nginx-server.conf:nginx-server.conf yandex/gixy nginx-server.conf

      - name: Lint Code Base (PR against development branch)
        # yamllint disable-line rule:line-length
        if: github.event_name == 'pull_request' && github.base_ref == 'development'
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: ${{ github.base_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Code Base (against PR base branch)
        # yamllint disable-line rule:line-length
        if: github.event_name == 'pull_request' && github.base_ref != 'development'
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.base_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Code Base (against current branch)
        if: github.event_name == 'push'
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.head_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
